baseURL               = "https://1024.link/"
languageCode          = "zh-CN"
title                 = "1024 LINK"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录


[params]
    author        = "苏格拉弟"
    description   = "站点导航 求职招聘"
    personSite    = "https://scny57ff1qdh.feishu.cn/share/base/form/shrcn5GmI2UKcDC6OX16SF1f7Jb"
    jobJD         = "https://scny57ff1qdh.feishu.cn/share/base/form/shrcnzjBFsP6TmSsE4GEXOH9Jie"      # 左侧导航栏的"网站提交"
    about         = "./about"	          # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/sugerlad"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "1024 LINK"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/link-favicon.ico"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务
    fancybox      = true                                        # 使用 Fancybox 实现图片灯箱/放大功能

[params.seo]    
    baiduhmid       = ''	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 


[params.images]
    favicon           = "assets/images/link-favicon.ico"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/expand-link.png"
    logoExpandDark    = "assets/images/expand-link.png"
    logoCollapseLight = "assets/images/link-favicon.ico"
    logoCollapseDark  = "assets/images/link-favicon.ico"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：sugerlad###outlook.com <br/>&copy; 2025 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [Sugerlad](https://www.1024.link/)<br/>'
